version: 2

jobs:
  deploy:
    docker:
      - image: circleci/node:12.14.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npx semantic-release

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          context: reaction-publish-semantic-release
          filters:
            branches:
              only: trunk
